

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SChat
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class SChatDataBaseEntities : DbContext
{
    public SChatDataBaseEntities()
        : base("name=SChatDataBaseEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Chat> Chat { get; set; }

    public virtual DbSet<Message> Message { get; set; }

    public virtual DbSet<User> User { get; set; }

    public virtual DbSet<UserChat> UserChat { get; set; }

}

}

